version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  imgsrv:
    network_mode: bridge
    image: imgsrv:test
    ports:
      - "80:80"
    volumes:
      - "./config.json:/config.json"
    command: ["/imgsrv"]
    depends_on:
      - mongodb
      - kafka